#!/bin/sh

runtests() {
  # True
  assert '[ "3" = "3" ]' [ "3" = "3" ]
  assert '[ "3" != "three" ]' [ "3" != "three" ]
  assert '[ -e urchin ]' [ -e urchin ]
  assert '( ! rmdir / )' ( ! rmdir / )

  # False
  assert '[ "3" = "4" ]' [ "3" = "4" ]
  assert '[ "three" != "three" ]' [ "three" != "three" ]
  assert '[ -e not_a_file ]' [ -e not_a_file ]

  # Error
  assert '( rmdir / )' ( rmdir / )
  assert gobbledygook gobbledygook
}
