#!/bin/sh

runtests() {
  # True
  assert '' [ "3" = "3" ]
  assert '' [ "3" != "three" ]
  assert 'The urchin script exists.' [ -e urchin ]
  rmdir_root_fails=false
  ! (rmdir / > /dev/null 2>&1) && rmdir_root_fails=true
  assert 'Cannot rmdir /' $rmdir_root_fails

# Why doesn't this work?
# assert '' '! rmdir /'

  # Errors
# rmdir /

  # False
  assert '' [ "3" = "4" ]
  assert '' [ "three" != "three" ]
  assert '' [ -e not_a_file ]
  rmdir_root_succeeds=true
  (rmdir / > /dev/null 2>&1) || rmdir_root_succeeds=false
  assert 'Can rmdir /' $rmdir_root_succeeds

  # Error
# assert '( rmdir / )' ( rmdir / )
# assert gobbledygook gobbledygook
}
